kind: Service
apiVersion: v1
metadata:
  # labels:
  #   app: name-brainstormulator
  name: "{{ .Release.Name }}-name-brainstormulator"
  namespace: nb
spec:
  # type: ClusterIP
  # sessionAffinity: None
  selector:
    app: name-brainstormulator
  ports:
    - protocol: TCP
      port: {{ .Values.deploy.service.port }}
      targetPort: {{ .Values.deploy.service.targetPort }}